<form action="" method="POST">
    <label>Описание
        <br>
        <input name="description" type="text" style="width: 50em;">
    </label>
    <label>Теги (через запятую)
        <br>
        <input name="tags" type="text" style="width: 25em;">
    </label>
    <label>Сумма
        <br>
        <input name="value" type="text" value="100.00" style="width: 7em;">
        <input name="type" type="radio" value="1" checked>
        <span class="money_in">прибыль</span>
        <input name="type" type="radio" value="1">
        <span class="money_out">расход</span>
    </label>
    <label>Дата
        <br>
        <input name="value" type="text" value="10.07.2010 10:30" style="width: 10em;">
    </label>
    <label>
        <input type="submit" value="Сохранить">
    </label>
</form>