<!DOCTYPE html>
<html>
    <head>
        <title>
            <?php echo self::get_title() ?>
        </title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <link rel="stylesheet" type="text/css" href="design/style.css" />
    </head>
    <body>
        <div id="wrap">
            <div id="side_bar">
            </div>
            <div id="content">
                <?php echo $content ?>
            </div>
            <div class="clear"></div>
            <div id="footer">© gd ∞</div>
        </div>
    </body>
</html>