<h1><?php echo ($form_data['id'] == 0) ? 'Новая запись' : 'Правка' ?></h1>

<form action="" method="POST">
    <label>Описание
        <br>
        <input
            onfocus="if(this.value=='нет описания ...') this.value='';"
            onblur="if(this.value=='') this.value='нет описания ...';"
            name="description" type="text" style="width: 100%;" value="<?php echo $form_data['description'] ?>">
    </label>
    <div class="note">любой текст, не более 300 символов</div>
    <label>Теги
        <br>
        <input name="tags" id="tags_input" type="text" style="width: 560px;" value="<?php echo $form_data['tags'] ?>">
    </label>
    <div class="note">через запятую, пример: <i>зарплата, основная работа, на карточку</i></div>
    <div id="tag_list"></div>
    <label>Сумма
        <br>
        <input onfocus="if(this.value=='0') this.value='';"
               onblur="if(this.value=='') this.value='0';"
               name="value" type="text" value="<?php echo $form_data['value'] ?>"
               style="width: 7em; text-align: right;">
        <input name="type" type="radio" value="1" <?php echo $form_data['type'] ? 'checked' : '' ?>>
        <span class="money_in">прибыль</span>
        <input name="type" type="radio" value="0" <?php echo !$form_data['type'] ? 'checked' : '' ?>>
        <span class="money_out">расход</span>
    </label>
    <div class="note">примеры: <i>100.42, 100,42, 5100, 5 100, 9 999.99</i></div>
    <label for="date_input">Дата</label>
    <div class="cal_wrap">
        <input id="date_input" class="date_input" name="date" type="text" value="<?php echo $form_data['date'] ?>">
        <div id="toggle_cal" class="toggle_cal"></div>
        <div id="calendar" class="calendar"></div>
    </div>

    <br><br><input type="submit" value="Сохранить">
    <input type="hidden" name="id" value="<?php echo $form_data['id'] ?>">
</form>
<script type="text/javascript">
new function() {

    /* Список тегов для удобного добавления
     */
    var tag_list = [<?php echo $tag_list; ?>];

    var tag_list_div = document.getElementById('tag_list');
    var tags_input = document.getElementById('tags_input');

    var add_tag = function() {
        tags_input.value += ((tags_input.value == '') ? '' : ', ') + this.innerHTML;
    }

    for (i = 0; i < tag_list.length; i++) {
        var newSpan = document.createElement('span');
        newSpan.innerHTML = tag_list[i];
        newSpan.onclick = add_tag;

        tag_list_div.appendChild(newSpan);
        tag_list_div.appendChild(document.createTextNode(" "));
    }

    /* Подключение календарика
     */
    new Kalender('date_input', 'calendar', 'toggle_cal');
}();
</script>