<h1><?php echo ($form_data['id'] == 0) ? 'Новая запись' : 'Правка' ?></h1>

<form action="" method="POST">
    <label>Описание
        <br>
        <input
            onfocus="if(this.value=='нет описания ...')this.value='';"
            onblur="if(this.value=='') this.value='нет описания ...';"
            name="description" type="text" style="width: 100%;" value="<?php echo $form_data['description'] ?>">
    </label>
    <div class="note">любой текст, не более 300 символов</div>
    <label>Теги
        <br>
        <input name="tags" id="tags_input" type="text" style="width: 560px;" value="<?php echo $form_data['tags'] ?>">
    </label>
    <div class="note">через запятую, пример: <i>зарплата, основная работа, на карточку</i></div>
    <div id="tag_list"></div>
    <label>Сумма
        <br>
        <input name="value" type="text" value="<?php echo $form_data['value'] ?>" 
               style="width: 7em; text-align: right;">
        <input name="type" type="radio" value="1" <?php echo $form_data['type'] ? 'checked' : '' ?>>
        <span class="money_in">прибыль</span>
        <input name="type" type="radio" value="0" <?php echo !$form_data['type'] ? 'checked' : '' ?>>
        <span class="money_out">расход</span>
    </label>
    <div class="note">примеры: <i>100.42, 100,42, 5100, 5 100, 9 999.99</i></div>
    <label>Дата
        <br>
        <input name="date" type="text" value="<?php echo $form_data['date'] ?>" style="width: 200px;">
    </label>
    <div class="note"><a href="http://www.php.net/manual/en/datetime.formats.php">формат</a>,
        примеры: <i>2010:08:24 18:56:31, 1/17/2006, 10/27</i></div>
    <label>
        <input type="submit" value="Сохранить">
    </label>
    <input type="hidden" name="id" value="<?php echo $form_data['id'] ?>">
</form>
<script type="text/javascript">
new function() {
    var tag_list = [<?php echo $tag_list; ?>];

    var tag_list_div = document.getElementById('tag_list');
    var tags_input = document.getElementById('tags_input');

    var add_tag = function() {
        tags_input.value += ((tags_input.value == '') ? '' : ', ') + this.innerHTML;
    }

    for (i = 0; i < tag_list.length; i++) {
        var newSpan = document.createElement('span');
        newSpan.innerHTML = tag_list[i];
        newSpan.onclick = add_tag;

        tag_list_div.appendChild(newSpan);
        tag_list_div.appendChild(document.createTextNode(" "));
    }
}();
</script>