<!DOCTYPE html>
<html>
    <head>
        <title>
            <?php echo self::get_title() ?>
        </title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <link rel="stylesheet" type="text/css" href="design/style.css" />
        <link rel="shortcut icon" href="design/favicon.png" />
    </head>
    <body>
        <div id="wrap">

<?php while (Messages::hasMessages()): ?>
    <div class="message"><?php echo Messages::popMessage(); ?></div>
<?php endwhile; ?>
<?php while (Messages::hasWarnings()): ?>
    <div class="message warning"><?php echo Messages::popWarning(); ?></div>
<?php endwhile; ?>
<?php while (Messages::hasErrors()): ?>
     <div class="message error"><?php echo Messages::popError(); ?></div>
<?php endwhile; ?>

            <a href="<?php echo Util::getBaseUrl() ?>" id="site_logo"></a>
        
            <div class="clear"></div>

            <div id="wrap2">
            <?php echo $content ?>
            </div>

            <div class="clear"></div>
            <div id="footer">© gd ∞</div>
        </div>
    </body>
</html>


