<form action="" method="GET">
    Период:
    <a href="<?php echo $date_links['today'] ?>">сегодня</a>
    <a href="<?php echo $date_links['mouth'] ?>">этот месяц</a>
    <a href="<?php echo $date_links['year'] ?>">этот год</a>
    <a href="<?php echo $date_links['all'] ?>">все</a>
     / с
    <input name="date_start" type="text" value="<?php echo $date_start ?>"
           style="width: 10em;">
    по
    <input name="date_end" type="text" value="<?php echo $date_end ?>"
           style="width: 10em;">
    <input type="submit" value=" задать ">
    
    <br>
    <div class="note">образец: 2010:08:24 18:56:31</div>

<?php foreach ($hidden_inputs as $k => $v) : ?>
    <input name="<?php echo $k ?>" type="hidden" value="<?php echo $v ?>">
<?php endforeach; ?>
</form>

<?php if (count( $select ) > 0) {?>
<div class="select">
<?php foreach ($select as $value) {
    echo $value['text']; ?>
    <a href="<?php echo $value['link']?>">[x]</a><br>
<?php } ?>
</div>
<?php } ?>

<table class="events_list">
<?php foreach ($events_list as $e) : ?>
    <tr>
        <td class="description <?php echo $e['type_str'] ?>">
            <?php echo $e['description']?> <span class="tags_list">
            <?php  foreach ($e['tag_list'] as $tag) : ?>
                <a href="<?php echo $tag['link']?>"><?php echo $tag['name']?></a>
            <?php endforeach; ?>
            </span></td>
        <td class='value <?php echo $e['type_str'] ?>'>
        <?php printf($e['symbol'] . '%.0f', $e['value'])?></td>
        <td class="date"><?php echo Util::readlyTime($e['date']) ?></td>
        <td class="buttons">
            <a class="button edit" 
               href="<?php echo $e['edit_link']?>" title="правка"></a>
            <a class="button remove" 
               href="<?php echo $e['remove_link']?>"
               onclick="return confirm('Удалить запись?');" title="удалить"></a>
        </td>
    </tr>
<?php endforeach; ?>
</table>

<br>Итого:
<span class='money_in'><?php echo $total_in ?></span>
- <span class='money_out'><?php echo $total_out ?></span>
= <?php echo $total ?>

<!--div style="text-align: center; padding-top: 1em;">
<a href="#">← новее</a>
<a href="#">все</a>
<a href="#">старее →</a>
</div-->

<div style="text-align: right; padding-right: 42px;">
<a class="big_button green" href="<?php echo $new_button_link?>">Добавить</a>
</div>