<form action="" method="POST">
    <label>Описание:<br/>
        <input class="txt_input" type="text" name="description"
               value="<?php echo $form_data['description'] ?>"></label>
    <div class="between_br"></div>
    <label>Теги:<br/>
        <input id="tags_input" class="txt_input" type="text" name="tags"
               value="<?php echo $form_data['tags'] ?>"></label>
    <div id="tag_list" class="tag_list_on_edit_page"></div>
        <div class="between_br"></div>
    <label for="value_input0">Сумма:</label>
        <label><input type="radio" name="type" value="1"
               <?php echo $form_data['type'] ? 'checked' : '' ?>>прибыль</label>
        <label><input type="radio" name="type" value="0" 
               <?php echo!$form_data['type'] ? 'checked' : '' ?>>расход</label><br>
        <input id="value_input0" class="txt_input" type="text" name="value"
               value="<?php echo $form_data['value'] ?>">
    <div class="between_br"></div>
    <label>Дата:<br/>
        <input class="txt_input" type="text" name="date"
               value="<?php echo $form_data['date'] ?>"></label>
    <div class="between_br"></div>
    <input class="btn_input" type="submit" value="сохранить">
    <input type="hidden" name="id" value="<?php echo $form_data['id'] ?>">
</form>
<script type="text/javascript">
    new function() {

        /* Список тегов для удобного добавления
         */
        var tag_list = <?php echo $tag_list; ?>;

        var tag_list_div = document.getElementById('tag_list');
        var tags_input = document.getElementById('tags_input');

        var add_tag = function() {
            tags_input.value += ((tags_input.value == '') ? '' : ', ') + this.innerHTML;
        }

        for (i = 0; i < tag_list.length; i++) {
            var newSpan = document.createElement('span');
            newSpan.innerHTML = tag_list[i].name;
            newSpan.onclick = add_tag;
            newSpan.style.backgroundColor = tag_list[i].color;

            tag_list_div.appendChild(newSpan);
            tag_list_div.appendChild(document.createTextNode(" "));
        }
}();
</script>