<style>
.event {
    margin: 5px 0;
}
.edit_event,  .remove_event{
    padding: 5px;
    display: block;
    font-family: sans-serif;
    color: #000;
    text-decoration: none;
}
.edit_event {
    margin-right: 25px;
    background: #efefef;
    -moz-border-radius: 4px 0 0 4px;
    border-radius: 4px 0 0 4px;
}
.remove_event {
    background: #fec5c5;
    width: 15px;
    float: right;
    -moz-border-radius: 0 4px 4px 0;
    border-radius: 0 4px 4px 0;
}

</style>

<?php foreach ($last_events as $e): ?>

<div class="event">
    <a class="remove_event" href="remove.php?id=<?php echo $e['id']?>">X</a>
    <a class="edit_event" href="edit.php?id=<?php echo $e['id']?>">
        <?php echo $e['description']?>
        <span class="tags">
            (<?php echo $e['tags']?>)
        </span>
        <span class="value">
            <?php echo $e['value_str']?>
        </span>
        <span class="date">
            <?php echo $e['date_str']?>
        </span>
    </a>
</div>

<?php endforeach; ?>